id: P004254
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3CN540
  title: སྡོམ་གསུམ་འཇམ་དབྱངས་བླ་མའི་དགོངས་རྒྱན་སོགས།
  author: ''
  volumes:
    89b303e43c1b44059b62cf91de153d82:
      image_group_id: I3CN3782
      title: ''
      volume_number: 1
      total_pages: 174
      base_file: v001.txt
